import re

with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

# For lines 968 and 981 we already fixed text-small text-muted, let's also fix quests
# The quest description is generated by JS, let's check app.js
